version: "3"
services:
 springBootApp:
    image: saiyeshwanth009/student-details:1.0
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - POSTGRES_HOST=docker-postgres-springboot-microservices-db-1 #domain  name
    ports:
      - "9015:9012"
      - "9013:9012"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: unless-stopped
 postgresDb:
  image: postgres:15.0
  container_name: docker-postgres-springboot-microservices-db-1
  ports:
   - "5432:5432"
  networks:
   - network
  volumes:
   - volume:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=159S@iYeshu*
   - POSTGRES_DB=Mid_Project
networks:
  network:
volumes:
  volume: